name: Bel Canto Music School
favicon: null
layout_spectrum: 0.54031
typography_spectrum: 0.9375220709480345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050503'
    - '#67553f'
    - '#b49984'
    - '#e5cba6'
  brandStrength: 0.3970573367550969
  lightness: 0.5368684707209468
  saturation: 0.2491352881770581
  rhythmicContrast: 0.5067441249266267
purpose: []
