name: Bel Canto Music School
favicon: null
layout_spectrum: 0.35726
typography_spectrum: 0.76989
title: Bel Canto Music School - Violin and Piano Lessons in Bristol
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050503'
    - '#67553f'
    - '#b49984'
    - '#e5cba6'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.2491352881770581
  rhythmicContrast: 0.5
purpose: []
